# Generated by Django 3.2.13 on 2022-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=50)),
                ('tekanan', models.IntegerField(max_length=20)),
                ('penggunaan', models.IntegerField(max_length=20)),
                ('limit', models.IntegerField(max_length=20)),
            ],
        ),
    ]
