# Generated by Django 3.2.13 on 2022-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='penggunaan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='tekanan',
            field=models.IntegerField(),
        ),
    ]
