# Generated by Django 3.2.13 on 2022-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_auto_20220505_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerid',
            name='customer_join',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customerid',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
    ]
