# Generated by Django 3.2.13 on 2022-06-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_regis', '0001_initial'),
        ('dashboard_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('limitMonthly', models.IntegerField(verbose_name=999999999)),
                ('usageMonthly', models.IntegerField(verbose_name=999999999)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_regis.datacustomer')),
            ],
        ),
    ]
