# Generated by Django 3.2.13 on 2022-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_detail', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlog',
            name='limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='usage',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='limitMonthly',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='usageMonthly',
            field=models.BigIntegerField(),
        ),
    ]
