# Generated by Django 3.2.13 on 2022-06-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_detail', '0003_auto_20220611_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlog',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='tanggal',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_detail.customerlog'),
        ),
    ]
