# Generated by Django 3.2.13 on 2022-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_detail', '0005_auto_20220702_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='month',
        ),
        migrations.AddField(
            model_name='history',
            name='month',
            field=models.CharField(default=int, max_length=10),
            preserve_default=False,
        ),
    ]
