# Generated by Django 3.2.13 on 2022-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenId', models.CharField(max_length=10)),
                ('tokenValue', models.CharField(max_length=10)),
                ('statusToken', models.BooleanField()),
            ],
        ),
    ]
