# Generated by Django 3.2.13 on 2022-06-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_detail', '0004_auto_20220615_2217'),
        ('dashboard_regis', '0003_auto_20220615_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billpay',
            fields=[
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard_regis.datacustomer')),
                ('billpay', models.IntegerField()),
                ('billpayStatus', models.CharField(max_length=10)),
                ('customerLog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard_detail.customerlog')),
            ],
        ),
    ]
