# Generated by Django 3.2.13 on 2022-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_detail', '0005_auto_20220702_0102'),
        ('dashboard_billpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpay',
            name='customerLog',
        ),
        migrations.AddField(
            model_name='billpay',
            name='customerLog',
            field=models.ManyToManyField(db_column='tanggal', to='dashboard_detail.customerLog'),
        ),
    ]
