# Generated by Django 3.2.13 on 2022-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_detail', '0006_auto_20220702_1315'),
        ('dashboard_billpay', '0002_auto_20220702_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpay',
            name='customerLog',
        ),
        migrations.AddField(
            model_name='billpay',
            name='month',
            field=models.ManyToManyField(db_column='month', to='dashboard_detail.History'),
        ),
    ]
