# Generated by Django 3.2.13 on 2022-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_regis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacustomer',
            name='phoneNumber',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
