# Generated by Django 3.2.13 on 2022-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_regis', '0002_alter_datacustomer_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacustomer',
            name='id',
        ),
        migrations.AlterField(
            model_name='datacustomer',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datacustomer',
            name='idCustomer',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datacustomer',
            name='phoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
