# Generated by Django 3.2.13 on 2022-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contactUs', models.CharField(max_length=50)),
                ('email_contactUs', models.EmailField(max_length=254)),
                ('subject_contactUs', models.CharField(max_length=100)),
                ('message_contactUs', models.CharField(max_length=1000)),
            ],
        ),
    ]
